import React from "react";
import PageHeader from "../CommenComponents/PageHeader";

const TermsAndConditions = () => {
  return (
    <>
      <PageHeader title="Terms & Conditions" />

      <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-10 text-gray-700 leading-relaxed space-y-8">
        <section>
          <h1 className="text-3xl font-bold text-primary-dark mb-4">Terms & Conditions</h1>

          <p>
            Welcome to Life Ledger, your personal finance and memory management platform. By using this website,
            you agree to the following Terms & Conditions. These terms apply to all visitors, registered users,
            and anyone using our services to manage expenses, memories, diaries, reminders, and related records.
          </p>

          <p className="mt-3">
            If you do not agree with these terms, please do not continue using the platform. We may update these
            terms from time to time, and continued use after updates indicates your acceptance of the revised terms.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-2">1. Platform Usage</h2>
          <p>
            Users may use Life Ledger for lawful personal financial tracking, memory recording, diary entries,
            reminders, and related management tasks. You agree not to misuse the platform or interfere with its
            performance, security, or availability.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-2">2. User Accounts</h2>
          <p>
            To access certain features, users may create an account. You are responsible for securing your login
            details and maintaining the accuracy of the information you provide. Any activity carried out through
            your account is your responsibility.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-2">3. Expense & Record Information</h2>
          <p>
            We strive to keep your expense records, memory entries, calendar data, and related information accurate.
            However, some details may vary due to manual input, device settings, time zones, or syncing behavior.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-2">4. Data Accuracy</h2>
          <p>
            The application helps organize finances and memories, but the final responsibility for the correctness of
            entered information lies with the user. We recommend reviewing submitted data before relying on reports or
            summaries generated by the platform.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-2">5. Privacy & Data Protection</h2>
          <p>
            Personal data entered into Life Ledger is handled with care and used only to provide the requested service,
            improve user experience, and support account functionality. We do not sell personal information to third parties.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-2">6. Content Ownership</h2>
          <p>
            You retain ownership of the content you add to the platform, including expense records, diary entries,
            memories, uploads, and notes. By storing them in Life Ledger, you provide us permission to process and store
            them only as needed to deliver the service.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-2">7. Service Availability</h2>
          <p>
            We aim to keep the service available and functional, but interruptions may occur due to updates, maintenance,
            technical issues, or external factors beyond our control. We do not guarantee uninterrupted access.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-2">8. Account Suspension</h2>
          <p>
            We reserve the right to suspend or restrict access if a user violates these terms, misuses the platform,
            attempts unauthorized access, or engages in fraudulent or harmful activity.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-2">9. Limitation of Liability</h2>
          <p>
            Life Ledger is provided on an “as is” basis. We are not liable for losses arising from inaccurate data entry,
            lost records, sync delays, or service disruptions unrelated to our direct control.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-2">10. Contact</h2>
          <p>
            For questions or concerns regarding these terms or your account, please contact the platform administrator
            or support team through the official communication channels provided within the app.
          </p>
        </section>
      </div>
    </>
  );
};

export default TermsAndConditions;
          </p>
        </section>

        {/* Force Majeure */}
        <section>
          <h2 className="text-xl font-semibold mb-2">14. Force Majeure</h2>

          <p>
            We shall not be liable for delays or failure to perform obligations
            due to events beyond our control such as natural disasters,
            pandemics, transportation disruptions, or government restrictions.
          </p>
        </section>

        {/* Governing Law */}
        <section>
          <h2 className="text-xl font-semibold mb-2">15. Governing Law</h2>

          <p>
            These Terms & Conditions are governed by the laws of India. Any
            disputes shall be subject to the jurisdiction of courts in Tamil
            Nadu.
          </p>
        </section>

      </div>
    </>
  );
};

export default TermsAndConditions;